In [1]:
import findspark
spark_home = "/usr/local/spark"
findspark.init(spark_home)

import geopyspark as gps
import numpy as np

from pyspark import SparkContext
from shapely.geometry import Point, MultiPolygon, LineString, box

In [2]:
conf = gps.geopyspark_conf(master="local[*]", appName="map-algebra")
pysc = SparkContext(conf=conf)

In [3]:
# Setting up the data

cells = np.array([[[3, 4, 1, 1, 1],
                   [7, 4, 0, 1, 0],
                   [3, 3, 7, 7, 1],
                   [0, 7, 2, 0, 0],
                   [6, 6, 6, 5, 5]]], dtype='int32')

extent = gps.ProjectedExtent(extent = gps.Extent(0, 0, 5, 5), epsg=4326)

layer = [(extent, gps.Tile.from_numpy_array(numpy_array=cells))]
  
rdd = pysc.parallelize(layer)
raster_layer = gps.RasterLayer.from_numpy_rdd(gps.LayerType.SPATIAL, rdd)
tiled_layer = raster_layer.tile_to_layout(layout=gps.LocalLayout(tile_size=5))

# Map Algebra

Given a set of raster layers, it may be desirable to combine and filter the content of those layers.  This is the function of _map algebra_.  Two classes of map algebra operations are provided by GeoPySpark: _local_ and _focal_ operations.  Local operations individually consider the pixels or cells of one or more rasters, applying a function to the corresponding cell values.  For example, adding two rasters' pixel values to form a new layer is a local operation.

Focal operations consider a region around each pixel of an input raster and apply an operation to each region.  The result of that operation is stored in the corresponding pixel of the output raster.  For example, one might weight a 5x5 region centered at a pixel according to a 2d Gaussian to effect a blurring of the input raster.  One might consider this roughly equivalent to a 2d convolution operation.

**Note:** Map algebra operations work only on `TiledRasterLayer`s, and if a local operation requires multiple inputs, those inputs must have the same layout and projection.

**Note**: Throughout this guide, this `.lookup(0, 0)[0].cells` is used on the resulting layer. This call simply retrieves the numpy array of the first tile within the layer.

## Local Operations

Local operations on `TiledRasterLayer`s can use `int`s, `float`s, or other `TiledRasterLayer`s. `+`, `-`, `*`, and `/` are all of the local operations that currently supported.

In [4]:
tiled_layer.lookup(0, 0)[0].cells

array([[[3, 4, 1, 1, 1],
        [7, 4, 0, 1, 0],
        [3, 3, 7, 7, 1],
        [0, 7, 2, 0, 0],
        [6, 6, 6, 5, 5]]], dtype=int32)

In [5]:
(tiled_layer + 1).lookup(0, 0)[0].cells

array([[[4, 5, 2, 2, 2],
        [8, 5, 1, 2, 1],
        [4, 4, 8, 8, 2],
        [1, 8, 3, 1, 1],
        [7, 7, 7, 6, 6]]], dtype=int32)

In [6]:
(2 - (tiled_layer * 3)).lookup(0, 0)[0].cells

array([[[ 7, 10,  1,  1,  1],
        [19, 10, -2,  1, -2],
        [ 7,  7, 19, 19,  1],
        [-2, 19,  4, -2, -2],
        [16, 16, 16, 13, 13]]], dtype=int32)

In [7]:
((tiled_layer + tiled_layer) / (tiled_layer + 1)).lookup(0, 0)[0].cells

array([[[1, 1, 1, 1, 1],
        [1, 1, 0, 1, 0],
        [1, 1, 1, 1, 1],
        [0, 1, 1, 0, 0],
        [1, 1, 1, 1, 1]]], dtype=int32)

`Pyramid`s can also be used in local operations. The types that can be used in local operations with `Pyramid`s are: `int`s, `float`s, `TiledRasterLayer`s, and other `Pyramid`s.

**Note**: Like with `TiledRasterLayer`, performing calculations on multiple `Pyramid`s or `TiledRasterLayer`s means they must all have the same layout and projection.

In [8]:
# Creating out Pyramid
pyramid = tiled_layer.pyramid()
pyramid

Pyramid(layer_type=LayerType.SPATIAL, max_zoom=0, num_levels=1, is_cached=False)

In [9]:
pyramid + 1

Pyramid(layer_type=LayerType.SPATIAL, max_zoom=0, num_levels=1, is_cached=False)

In [12]:
(pyramid - tiled_layer) * 2

Pyramid(layer_type=LayerType.SPATIAL, max_zoom=0, num_levels=1, is_cached=False)

## Focal Operations

Focal operations are performed in GeoPySpark by executing a given operation on a neighborhood throughout each tile in the layer. One can select a neighborhood to use from the `Neighborhood` enum class. Likewise, an operation can be choosen from the enum class, `Operation`.

In [13]:
# This creates an instance of Square with an extent of 1. This means that each operation will be performed on a 3x3
# neighborhood.

'''
A square neighborhood with an extent of 1.
o = source cell
x = cells that fall within the neighbhorhood

x x x
x o x
x x x
'''

square = gps.Square(extent=1)

In [15]:
square

Square(extent=1.0)

In [14]:
# Values in the original Tile
tiled_layer.lookup(0, 0)[0].cells

array([[[3, 4, 1, 1, 1],
        [7, 4, 0, 1, 0],
        [3, 3, 7, 7, 1],
        [0, 7, 2, 0, 0],
        [6, 6, 6, 5, 5]]], dtype=int32)

#### Mean

In [16]:
tiled_layer.focal(operation=gps.Operation.MEAN, neighborhood=square).lookup(0, 0)[0].cells

array([[[ 4.5       ,  3.16666667,  1.83333333,  0.66666667,  0.75      ],
        [ 4.        ,  3.55555556,  3.11111111,  2.11111111,  1.83333333],
        [ 4.        ,  3.66666667,  3.44444444,  2.        ,  1.5       ],
        [ 4.16666667,  4.44444444,  4.77777778,  3.66666667,  3.        ],
        [ 4.75      ,  4.5       ,  4.33333333,  3.        ,  2.5       ]]])

#### Median

In [17]:
tiled_layer.focal(operation=gps.Operation.MEDIAN, neighborhood=square).lookup(0, 0)[0].cells

array([[[4, 3, 1, 1, 1],
        [3, 3, 3, 1, 1],
        [3, 3, 3, 1, 0],
        [4, 6, 6, 5, 3],
        [6, 6, 5, 3, 2]]], dtype=int32)

#### Mode

In [18]:
tiled_layer.focal(operation=gps.Operation.MODE, neighborhood=square).lookup(0, 0)[0].cells

array([[[          4,           4,           1,           1,           1],
        [          3,           3,           1,           1,           1],
        [-2147483648,           7,           7,           0,           0],
        [-2147483648,           6,           7, -2147483648, -2147483648],
        [          6,           6,           6, -2147483648, -2147483648]]], dtype=int32)

#### Sum

In [19]:
tiled_layer.focal(operation=gps.Operation.SUM, neighborhood=square).lookup(0, 0)[0].cells

array([[[18, 19, 11,  4,  3],
        [24, 32, 28, 19, 11],
        [24, 33, 31, 18,  9],
        [25, 40, 43, 33, 18],
        [19, 27, 26, 18, 10]]], dtype=int32)

#### Standard Deviation

In [20]:
tiled_layer.focal(operation=gps.Operation.STANDARD_DEVIATION, neighborhood=square).lookup(0, 0)[0].cells

array([[[ 1.5       ,  2.26691175,  1.57233019,  0.47140452,  0.4330127 ],
        [ 1.41421356,  2.2166597 ,  2.46956786,  2.64341717,  2.33927814],
        [ 2.44948974,  2.66666667,  2.79329002,  2.74873708,  2.5       ],
        [ 2.40947205,  2.36225463,  2.39340658,  2.74873708,  2.76887462],
        [ 2.77263413,  2.56580072,  2.49443826,  2.44948974,  2.5       ]]])

#### Min

In [21]:
tiled_layer.focal(operation=gps.Operation.MIN, neighborhood=square).lookup(0, 0)[0].cells

array([[[3, 0, 0, 0, 0],
        [3, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int32)

#### Max

In [22]:
tiled_layer.focal(operation=gps.Operation.MAX, neighborhood=square).lookup(0, 0)[0].cells

array([[[7, 7, 4, 1, 1],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 6, 5]]], dtype=int32)

#### Slope

In [23]:
tiled_layer.focal(operation=gps.Operation.SLOPE, neighborhood=square).lookup(0, 0)[0].cells

array([[[ 49.85993385,  54.08471312,  48.54094085,  14.03624347,
          14.03624347],
        [ 58.46788753,  57.68846676,  65.70243656,  67.13791086,
          55.55009801],
        [ 56.4920663 ,  21.56812944,  38.3288181 ,  60.2551187 ,
          54.08471312],
        [ 72.05231495,  54.73561032,  54.08471312,  54.08471312,
          59.19301888],
        [ 54.08471312,  45.86825079,  63.16221244,  66.54586268,
          63.16221244]]])

#### Aspect

In [24]:
tiled_layer.focal(operation=gps.Operation.ASPECT, neighborhood=square).lookup(0, 0)[0].cells

array([[[ 108.43494882,  354.80557109,    6.34019175,  270.        ,  270.        ],
        [ 355.60129465,   18.43494882,   73.61045967,   71.56505118,
           30.96375653],
        [ 245.55604522,  161.56505118,   71.56505118,    0.        ,
          354.80557109],
        [ 158.62937773,  135.        ,  354.80557109,  354.80557109,
           26.56505118],
        [  95.19442891,  104.03624347,   55.30484647,   77.47119229,
          108.43494882]]])

# Miscellaneous Raster Operations

There are other means to extract information from rasters and to create rasters that need to be presented.  These are _polygonal summaries_, _cost distance_, and _rasterization_.

## Polygonal Summary Methods

In addition to local and focal operations, polygonal summaries can also be performed on `TiledRasterLayer`s. These are operations that are executed in the areas that intersect a given geometry and the layer.

**Note**: It is important the given geometry is in the same projection as the layer. If they are not, then either incorrect and/or only partial results will be returned.

In [25]:
tiled_layer.layer_metadata

### Polygonal Min

In [26]:
poly_min = box(0.0, 0.0, 1.0, 1.0)
tiled_layer.polygonal_min(geometry=poly_min, data_type=int)

[6]

### Polygonal Max

In [27]:
poly_max = box(1.0, 0.0, 2.0, 2.5)
tiled_layer.polygonal_min(geometry=poly_max, data_type=int)

[3]

### Polygonal Sum

In [28]:
poly_sum = box(0.0, 0.0, 1.0, 1.0)
tiled_layer.polygonal_min(geometry=poly_sum, data_type=int)

[6]

### Polygonal Mean

In [29]:
poly_max = box(1.0, 0.0, 2.0, 2.0)
tiled_layer.polygonal_min(geometry=poly_max, data_type=int)

[6]

## Cost Distance

`cost_distance` is an iterative method for approximating the weighted distance from a raster cell to a given geometry. The `cost_distance` function takes in a geometry and a “friction layer” which essentially describes how difficult it is to traverse each raster cell. Cells that fall within the geometry have a final cost of zero, while friction cells that contain noData values will correspond to noData values in the final result. All other cells have a value that describes the minimum cost of traversing from that cell to the geometry. If the friction layer is uniform, this function approximates the Euclidean distance, modulo some scalar value.

In [30]:
cost_distance_cells = np.array([[[1.0, 1.0, 1.0, 1.0, 1.0],
                                 [1.0, 1.0, 1.0, 1.0, 1.0],
                                 [1.0, 1.0, 1.0, 1.0, 1.0],
                                 [1.0, 1.0, 1.0, 1.0, 1.0],
                                 [1.0, 1.0, 1.0, 1.0, 0.0]]])

tile = gps.Tile.from_numpy_array(numpy_array=cost_distance_cells, no_data_value=-1.0)
cost_distance_extent = gps.ProjectedExtent(extent=gps.Extent(xmin=0.0, ymin=0.0, xmax=5.0, ymax=5.0), epsg=4326)
cost_distance_layer = [(cost_distance_extent, tile)]

cost_distance_rdd = pysc.parallelize(cost_distance_layer)
cost_distance_raster_layer = gps.RasterLayer.from_numpy_rdd(gps.LayerType.SPATIAL, cost_distance_rdd)
cost_distance_tiled_layer = cost_distance_raster_layer.tile_to_layout(layout=gps.LocalLayout(tile_size=5))

In [31]:
result = gps.cost_distance(friction_layer=cost_distance_tiled_layer, geometries=[Point(0.0, 5.0)], max_distance=144000.0)
result.to_numpy_rdd().first()[1].cells[0]

array([[      0.        ,  111319.49079327,              nan,
                     nan,              nan],
       [ 111319.49079327,              nan,              nan,
                     nan,              nan],
       [             nan,              nan,              nan,
                     nan,              nan],
       [             nan,              nan,              nan,
                     nan,              nan],
       [             nan,              nan,              nan,
                     nan,              nan]])

## Rasterization

It may be desirable to convert vector data into a raster layer.  For this, we provide the `rasterize` function, which determines the set of pixel values covered by each vector element, and assigns a supplied value to that set of pixels in a target raster.  If, for example, one had a set of polygons representing counties in the US, and a value for, say, the median income within each county, a raster could be made representing these data.

GeoPySpark's `rasterize` function takes a list of any number of Shapely geometries, converts them to rasters, tiles the rasters to a given layout, and then produces a `TiledRasterLayer` with these tiled values.

### Rasterize MultiPolygons

In [32]:
raster_poly_1 = box(0.0, 0.0, 5.0, 10.0)
raster_poly_2 = box(3.0, 6.0, 15.0, 20.0)
raster_poly_3 = box(13.5, 17.0, 30.0, 20.0)

raster_multi_poly = MultiPolygon([raster_poly_1, raster_poly_2, raster_poly_3])

In [35]:
# Creates a TiledRasterLayer that contains the MultiPolygon with a CRS of EPSG:3857 at zoom level 5.
gps.rasterize(geoms=[raster_multi_poly], crs=4326, zoom=5, fill_value=1)

TiledRasterLayer(layer_type=LayerType.SPATIAL, zoom_level=5, is_floating_point_layer=True)

### Rasterize LineStrings

In [36]:
line_1 = LineString(((0.0, 0.0), (0.0, 5.0)))
line_2 = LineString(((7.0, 5.0), (9.0, 12.0), (12.5, 15.0)))
line_3 = LineString(((12.0, 13.0), (14.5, 20.0)))

In [37]:
# Creates a TiledRasterLayer whose cells have a data type of int16.
gps.rasterize(geoms=[line_1, line_2, line_3], crs=4326, zoom=3, fill_value=2, cell_type=gps.CellType.INT16)

TiledRasterLayer(layer_type=LayerType.SPATIAL, zoom_level=3, is_floating_point_layer=False)

### Rasterize Polygons and LineStrings

In [40]:
# Creates a TiledRasterLayer with both the LineStrings and the MultiPolygon
gps.rasterize(geoms=[line_1, line_2, line_3, raster_multi_poly], crs=4326, zoom=5, fill_value=2)

TiledRasterLayer(layer_type=LayerType.SPATIAL, zoom_level=5, is_floating_point_layer=True)

In [41]:
pysc.stop()